jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@v3
        with:
          api-token: ${{ secrets.SNYK_TOKEN }}
      - uses: snyk/actions/test@v3
      - name: Fail on high severity vulnerabilities
        if: steps.snyk-test.outputs.exit_code == 2
        run: exit 1
